name: Workflow JSONPlaceholder

on:
  push:
    branches:
      - main

env:
  STATE_BUCKET: statebenchmark

jobs:
  call-jsonplaceholder:
    runs-on: ubuntu-latest
    steps:
      - name: Set initial state
        run: |
            echo "{\"status\": \"${{ job.status }}\"}" > json_placeholder.json
      - name: Call JSONPlaceholder
        run: |
          curl https://jsonplaceholder.typicode.com/todos > response.json
          echo "{\"status\": \"$(cat response.json | jq '.title')\"}" > state_placeholder.json
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEY}}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESS }}
          aws-region: us-east-1
      - name: Save state to S3
        run: aws s3 cp state_placeholder.json s3://${{ env.STATE_BUCKET }}/state_placeholder.json

  call-githubactions:
    runs-on: ubuntu-latest
    steps:
      - name: Set initial state
        run: |
          echo "{\"status\": \"starting\"}" > state_githubactions.json
      - name: Call GitHub Actions
        run: |
          echo "{\"status\": \"${{ job.status }}\"}" > state_githubactions.json
          echo "{\"status\": \"${{ job }}\"}" > job_githubactions.json
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESS }}
          aws-region: us-east-1
      - name: Save state to S3
        run: aws s3 cp state_githubactions.json s3://${{ env.STATE_BUCKET }}/state_githubactions.json

      - name: Saving github action info
        run: |
          echo "{\"status\": \"starting\"}" > state.json
      - name: Call GitHub Actions
        run: |
          echo "{\"workflow\": \"${{ github.workflow }}\", \"action\": \"${{ github.action }}\", \"sha\": \"${{ github.sha }}\", \"ref\": \"${{ github.ref }}\", \"repository\": \"${{ github.repository }}\", \"event\": \"${{ github.event_name }}\", \"actor\": \"${{ github.actor }}\", \"job\": \"${{ github.job }}\", \"status\": \"${{ job.status }}\"}" > state.json
      - name: Save state to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --no-progress --exclude '*.git/*'
        env:
          AWS_S3_BUCKET: ${{ env.STATE_BUCKET }}
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETACCESS }}
      - name: Save workflow state to S3 final
        run: |
         echo "${{ toJson(steps) }}" > workflow_state.json
         aws s3 cp ./workflow_state.json s3://statebenchmark/workflow_state.json
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETACCESS }}
            AWS_REGION: us-east-1
            