name: Workflow JSONPlaceholder

on:
  push:
    branches:
      - main
env:
  STATE_BUCKET: statebenchmark

jobs:
  call-jsonplaceholder:
    runs-on: ubuntu-latest
    steps:
      - name: Call JSONPlaceholder
        run: |
          curl https://jsonplaceholder.typicode.com/todos > response.json
          echo "{\"status\": \"$(cat response.json | jq '.title')\"}" > state.json
      - name: Save state to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --no-progress --exclude '*.git/*'
        env:
          AWS_S3_BUCKET: ${{ env.STATE_BUCKET }}
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
