name: Workflow JSONPlaceholder

on:
  push:
    branches:
      - main

env:
  STATE_BUCKET: statebenchmark

jobs:
  call-jsonplaceholder:
    runs-on: ubuntu-latest
    steps:
      - name: Call JSONPlaceholder
        run: |
          curl https://jsonplaceholder.typicode.com/todos > response.json
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESS }}
          aws-region: us-east-1
  
      - name: Call GitHub Actions
        run: |
          echo "{\"workflow\": \"${{ github.workflow }}\", \"action\": \"${{ github.action }}\", \"sha\": \"${{ github.sha }}\", \"ref\": \"${{ github.ref }}\", \"repository\": \"${{ github.repository }}\", \"event\": \"${{ github.event_name }}\", \"actor\": \"${{ github.actor }}\", \"job\": \"${{ github }}\", \"status\": \"${{ job.status }}\"}" > state.json
  
      - name: Save state to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --no-progress --exclude '*.git/*'
        env:
          AWS_S3_BUCKET: ${{ env.STATE_BUCKET }}
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETACCESS }}
